# Generated by Django 3.2.5 on 2021-07-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Aguardando'), (1, 'Enviado')], default=0)),
                ('method', models.IntegerField(choices=[(1, 'E-mail'), (2, 'SMS'), (3, 'Push'), (4, 'WhatsApp')])),
                ('timestamp', models.DateTimeField()),
                ('receiver', models.CharField(max_length=60)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
